### ISSUE TITLE
Export2Pdf: Mfp3Encoder does not work in standalone mode

### ISSUE THREAD

**Issue by taulinger** [ldbv-by/bav4-nomigration#1337]
```
Error: No value found for 'SHORTENING_SERVICE_URL'
    at ProcessEnvConfigService.getValue (ProcessEnvConfigService.js:68:1)
    at ProcessEnvConfigService.getValueAsPath (ProcessEnvConfigService.js:78:1)
    at UrlService.bvvQrCodeProvider [as _qrCodeUrlProvider] (qrCodeUrlProvider.js:23:1)
    at UrlService.qrCode (UrlService.js:99:1)
    at BvvMfp3Encoder.encode (Mfp3Encoder.js:128:1)
    at async OlMfpHandler._encodeMap (OlMfpHandler.js:258:1)
```

**Comment by taulinger** [comment]
Calling  `UrlService#shorten` and `UrlService#qrCode` within `Mfp3Encoder` must be done within a try/catch block.
See also: https://github.com/ldbv-by/bav4-nomigration/blob/7cbed371f842349fc98bfb4758c4ebcb15e01472/src/modules/toolbox/components/shareButton/ShareButton.js#L50
